-- Prod Oracle views (CLAIMS_AI_RO schema) — documentation / interview reference.
-- Agent MCP server queries these with parameterized SQL only.

-- CREATE OR REPLACE VIEW CLAIMS_AI_RO.V_CLAIM_SUMMARY_FOR_AI AS
-- SELECT c.claim_uid AS claim_id, ...
-- FROM CLAIMS.claim_header c
-- JOIN PARTY.claimant p ON ...

-- CREATE OR REPLACE VIEW CLAIMS_AI_RO.V_PAYMENT_SUMMARY_FOR_AI AS ...
-- CREATE OR REPLACE VIEW CLAIMS_AI_RO.V_RESERVE_CONTEXT_FOR_AI AS ...
-- CREATE OR REPLACE VIEW CLAIMS_AI_RO.V_CLAIMANT_CONTEXT_FOR_AI AS ...
